			<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Seleccionar Cuenta</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
			
			<div class="row">
				<div class="col-md-2"></div>
				
				<div class="col-md-8">
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/redaccion@coonic.com">redaccion@coonic.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/contenidos@proyectoscoonic.com">contenidos@proyectoscoonic.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/mbahillo@coonic.com">mbahillo@coonic.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/jmvalino@coonic.com">jmvalino@coonic.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/adediego@coonic.com">adediego@coonic.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/unai.prieto@hotmail.com">unai.prieto@hotmail.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/cdoval@coonic.com">cdoval@coonic.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/ebenito@coonic.com">ebenito@coonic.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/desarrollo2@proyectoscoonic.com">desarrollo2@proyectoscoonic.com</a>
						</div>
					</div>
					<div class="col-md-12" style="background-color: #eee; border-bottom: solid 2px #bbb; margin-bottom: 15px;">
						<div style="padding: 25px 15px; color: #428bca;">
							<a href="<?php echo BASE_URL; ?>index/cuenta/desarrollo@coonic.com">desarrollo@coonic.com</a>
						</div>
					</div>
				</div>
				
				<div class="col-md-2"></div>
			</div>