			<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Conciertos Cancelados</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
			
			
			
			<div class="row">
				<div class="col-xs-1"></div>
				
				<div class="col-xs-10" style="margin-bottom: 15px;">
					<div class="row">
						<?php
									
						$datos = $this->listaConciertos;
						
						for($i=0;$i<count($datos);$i++):
							$bolo = $datos[$i];
							
							$fecha_actual = strtotime(date("d-m-Y 00:00:00",time()));
							$fecha_entrada = strtotime($bolo['dia'] ." 1:00:00");
							
							if($fecha_actual <= $fecha_entrada):
								?>
								<div class="col-md-12" style="background: #eee; margin-bottom: 25px; padding-top: 15px; padding-bottom: 15px;">
									<div class="col-md-12">
										<div class="row" style="padding-bottom: 10px;">
											<div class="col-xs-6">
												<button type="button" class="btn btn-danger btn-xs">Cancelado</button>
											</div>
											<div class="col-xs-6 text-right">
												<form method="POST" action="<?php echo BASE_URL; ?>musica/cancelados">
													<input type="hidden" name="canceladosVisto" value="1" />
													<input type="hidden" name="idVisto" value="<?php echo $bolo['idBolo']; ?>" />
													
													<button type="submit" class="btn btn-primary">Visto</button>
												</form>
											</div>
										</div>
									</div>
									
									<div class="col-md-12">
										<div class="form-group">
											<div class="input-group">
												<div class="input-group-addon"><strong>Artista</strong></div>
												<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $bolo['artista']; ?>">
											</div>
										</div>
									</div>
									
									<div class="col-md-6">
										<div class="form-group">
											<div class="input-group">
												<div class="input-group-addon"><strong>Sala</strong></div>
												<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $bolo['sala']; ?>">
											</div>
										</div>
										
										
										<div class="form-group">
											<div class="input-group">
												<div class="input-group-addon"><strong>URL_Sala</strong></div>
												<div class="input-group-addon"><a href="<?php echo $bolo['url_sala']; ?>" target="_blank"><strong>IR</strong></a></div>
												<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $bolo['url_sala']; ?>">
											</div>
										</div>
									</div>
									
									<div class="col-md-6">
										<div class="row">
											<div class="form-group col-md-6">
												<div class="input-group">
													<div class="input-group-addon"><strong>Dia</strong></div>
													<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $bolo['dia']; ?>">
												</div>
											</div>
											<div class="form-group col-md-6">
												<div class="input-group">
													<div class="input-group-addon"><strong>Hora</strong></div>
													<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $bolo['hora']; ?>">
												</div>
											</div>
										</div>
										
										
										
										<div class="form-group">
											<div class="input-group">
												<div class="input-group-addon"><strong>URL_Ticket</strong></div>
												<div class="input-group-addon"><a href="<?php echo $bolo['url_ticket']; ?>" target="_blank"><strong>IR</strong></a></div>
												<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $bolo['url_ticket']; ?>">
											</div>
										</div>
									</div>
									
									<div class="col-md-12">
										<div class="form-group">
											<div class="input-group">
												<div class="input-group-addon"><strong>URL_Imagen</strong></div>
												<div class="input-group-addon"><a href="<?php echo $bolo['url_img']; ?>" target="_blank"><strong>IR</strong></a></div>
												<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $bolo['url_img']; ?>">
											</div>
										</div>
									</div>
								</div>
								<?php
							endif;
						endfor;
						?>
					</div>
				</div>
				
				<div class="col-xs-1"></div>
			</div>