<?php

$meses = Array('Jan' => 1,
			   'Feb' => 2,
			   'Mar' => 3,
			   'Apr' => 4,
			   'May' => 5,
			   'Jun' => 6,
			   'Jul' => 7,
			   'Aug' => 8,
			   'Sep' => 9,
			   'Oct' => 10,
			   'Nov' => 11,
			   'Dec' => 12
			   );

			   
?>
			<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Capturar Conciertos</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
			
			<div class="row" style="padding-bottom: 30px;">
				<div class="col-md-6">
					<form name="" action="<?php echo BASE_URL; ?>musica/capturar" method="post">
						<input type="hidden" name="capturar" value="1" />
						<button type="submit" class="btn btn-primary">Generar</button>
					</form>
				</div>
				<div class="col-md-6 text-right">
					<?php
					
					if(Session::get('email') == 'desarrollo@coonic.com' OR Session::get('email') == 'desarrollo2@proyectoscoonic.com'):
						?>
						<form name="" action="<?php echo BASE_URL; ?>musica/capturar" method="post">
							<input type="hidden" name="purgar" value="1" />
							<button type="submit" class="btn btn-danger">PURGAR TABLAS</button>
						</form>
						<?php
					endif;
					?>
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-1"></div>
				
				<div class="col-md-10">
					<form name="" action="<?php echo BASE_URL; ?>musica/capturar" method="post">
						<?php
						
						$datos = $this->captura;
						
						if(count($datos) > 0):
						?>
						
						<!--<button type="submit" class="btn btn-default btn-lg btn-block" style="margin-bottom: 20px;">GUARDAR DATOS</button>-->
						
						<input type="hidden" name="guardar" value="1" />
				
						<?php
							$arrEnvioMail = Array();
							
							for($i=0;$i<count($datos);$i++):
								$cadena = '';
								
								$artista = $datos[$i];
								
								
								
								$sala 		= $artista['venue'];
								
								$id 		= $artista["id"];
								
								$nombre 	= $artista["artists"]['artist'];
								if(is_array($nombre) > 0) $nombre = $nombre[0];
								
								$local 		= $sala['name'];
								$webL 		= $sala['website'];
								if($webL == '') $webL = '#';
								
								$webT 		= $artista['website'];
								if($webT == '') $webT = '#';
								
								$fecha 		= $artista["startDate"];
								$fecha 		= explode(" ", $fecha);
								
								$fechaMod 	= 0;
								
								$dia 		= $fecha[3] ."-". $meses[$fecha[2]] ."-". $fecha[1];
								$hora 		= $fecha[4];
								
								$hora 		= explode(":", $hora);
								$hora 		= $hora[0] .":". $hora[1];
								
								
								$descripcion = html_entity_decode($artista['description']);
								$descripcion = str_replace('\n', "\n", $descripcion);
								//$descripcion = str_replace('<br />', "", $descripcion);
								$descripcion = str_replace('<p>', "", $descripcion);
								$descripcion = str_replace('</p>', "", $descripcion);
								$descripcion = str_replace('<div class="bbcode">', "", $descripcion);
								$descripcion = str_replace('</div>', "", $descripcion);
								
								
								
								
								$cancelado		= $artista['cancelled'];
								$web_cancelado 	= musicaModel::checkCandelado($id);
								
								if($cancelado == 1 OR $web_cancelado == 1)
									$cancelado = 1;
								
								$foto = $artista["image"][3]["#text"];
									if($foto == '')
										$foto = 'http://placehold.it/338x236';
									
								
								$cadena = $artista ."-". $local ."-". $dia ."-". $hora ."-". $webL ."-". $webT ."-". $foto ."-". $descripcion;
								$cadena = md5($cadena);
								
								
								$guardado = musicaModel::checkGuardado($id);
								$modificado = musicaModel::checkModificado($id, $cadena);
								$visto = musicaModel::checkVisto($id);
								
								$fecha_actual = strtotime(date("d-m-Y 00:00:00",time()));
								$fecha_entrada = strtotime($dia ." 1:00:00");
								
								if($fecha_actual <= $fecha_entrada):
									?>
										<div class="col-md-12" style="padding: 10px 0; margin-bottom: 20px; background: #eeeeee;">
											<div class="col-md-12" style="padding-top: 8px; padding-bottom: 15px;">
												<?php
												
												if($guardado == 0):
													?>
														<button type="button" class="btn btn-default btn-sm">SIN INSERTAR</button>
													<?php
												else:
													if($cancelado == 1):
														?>
															<button type="button" class="btn btn-danger btn-sm">CANCELADO</button>
														<?php
													else:
														if($modificado == 1):
															?>
																<button type="button" class="btn btn-warning btn-sm">MODIFICADO</button>
															<?php
														else:
															if($visto == 1):
																?>
																	<button type="button" class="btn btn-success btn-sm">INSERTADO</button>
																<?php
															else:
																?>
																	<button type="button" class="btn btn-info btn-sm">GUARDADO DB</button>
																<?php
															endif;
														endif;
													endif;
												endif;
												?>
											</div>
											
											<div class="col-md-6">
												<img src='<?php echo $foto; ?>' class="img-responsive" width='338' height='236' style="max-height: 400px;" /><br />
											</div>
											
											<div class="col-md-6">
												<div class="form-group">
													<div class="input-group">
														<div class="input-group-addon"><strong>Artista</strong></div>
														<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $nombre; ?>">
													</div>
												</div>
												
												<div class="form-group">
													<div class="input-group">
														<div class="input-group-addon"><strong>Dia</strong></div>
														<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $dia; ?>">
													</div>
												</div>
												
												<div class="form-group">
													<div class="input-group">
														<div class="input-group-addon"><strong>Hora</strong></div>
														<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $hora; ?>">
													</div>
												</div>
												
												<div class="form-group">
													<div class="input-group">
														<div class="input-group-addon"><strong>Sala</strong></div>
														<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $local; ?>">
													</div>
												</div>
												
												
												<div class="form-group">
													<div class="input-group">
														<div class="input-group-addon"><strong>URL SALA</strong></div>
														<div class="input-group-addon"><a href="<?php echo $webL; ?>" target="_blank"><strong>IR</strong></a></div>
														<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $webL ?>">
													</div>
												</div>
												
												<div class="form-group">
													<div class="input-group">
														<div class="input-group-addon"><strong>URL TICKET</strong></div>
														<div class="input-group-addon"><a href="<?php echo $webT; ?>" target="_blank"><strong>IR</strong></a></div>
														<input disabled style="background: #fff !important;" type="text" class="form-control" value="<?php echo $webT; ?>">
													</div>
												</div>
												
												
												
											</div>
											
											<div class="col-md-12">
												<b>Descripcion:</b> 
												
												<div class="well well-sm">
													<?php echo $descripcion; ?>
												</div>
											</div>
										</div>
									<?php
									if($guardado == 0 AND $cancelado == 0):
										musicaModel::setBolos($id, $nombre, $dia, $hora, $local, $webL, $webT, $foto, $descripcion, $cadena, 0, 0, $cancelado);
									else:
										if(($cancelado == 1 OR $modificado == 1)):
											$visto = musicaModel::checkVisto($id);
											if($visto == 1)
												$arrEnvioMail[] = $id;
										endif;
										
										if($cancelado == 1 AND $visto == 1):
											musicaModel::cancelBolos($id);
										else:
											if($modificado == 1):
												musicaModel::updateBolos($id, $nombre, $dia, $hora, $local, $webL, $webT, $foto, $descripcion, $cadena, 1, 0, $cancelado);
											endif;
										endif;
									endif;
								endif;
							endfor;
						
						
							musicaModel::sendEmails($arrEnvioMail);
						
						?>
						
						<input type="hidden" name="totalBolos" value="<?php echo count($datos); ?>" />
						
						
						<script>
							/*location.replace('<?php echo BASE_URL ."musica/capturar"; ?>');*/
						</script>
						<?php
						
						endif;
						
						?>
					</form>
				</div>
				
				<div class="col-md-1"></div>
			
			</div>