			<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Listado de Conciertos</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
			
			
			<div class="table-responsive">
				<table class="table table-striped table-bordered table-hover" id="dataTables-example">
					<thead>
						<tr>
							<th>Artista</th>
							<th>Dia</th>
							<th>Hora</th>
							<th>Sala</th>
							<th>url_sala</th>
							<th>url_ticket</th>
							<th>Descripcion</th>
						</tr>
					</thead>
					<tbody>
						<?php
						
						$datos = $this->listaConciertos;
						
						for($i=0;$i<count($datos);$i++):
							$bolo = $datos[$i];
							
							$fecha_actual = strtotime(date("d-m-Y 00:00:00",time()));
							$fecha_entrada = strtotime($bolo['dia'] ." 1:00:00");
							
							if($fecha_actual <= $fecha_entrada):
								$descripcion = html_entity_decode($bolo['descripcion']);
								$descripcion = str_replace('\n', "\n", $descripcion);
								$descripcion = str_replace('<br />', "\n", $descripcion);
								$descripcion = str_replace('<p>', "", $descripcion);
								$descripcion = str_replace('</p>', "", $descripcion);
								$descripcion = str_replace('<div class="bbcode">', "", $descripcion);
								$descripcion = str_replace('</div>', "", $descripcion);
								?>
								<tr >
									<td><?php echo $bolo['artista']; ?></td>
									<td><?php echo $bolo['dia']; ?></td>
									<td><?php echo $bolo['hora']; ?></td>
									<td><?php echo $bolo['sala']; ?></td>
									<td><input type="text" class="form-control" value="<?php echo $bolo['url_sala']; ?>" /></td>
									<td><input type="text" class="form-control" value="<?php echo $bolo['url_ticket']; ?>" /></td>
									<td><textarea class="form-control" rows="5"><?php echo $descripcion; ?></textarea></td>
								</tr>
								<?php
							endif;
						endfor;
						?>
					</tbody>
				</table>
			</div>
			<!-- /.table-responsive -->